version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/app
      - ./config:/var/www/config
      - ./routes:/var/www/routes
      - ./database:/var/www/database
      - ./resources:/var/www/resources
      - ./tests:/var/www/tests
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./package.json:/var/www/package.json
      - ./webpack.mix.js:/var/www/webpack.mix.js
      - ./.env:/var/www/.env
      - ./phpstan.neon:/var/www/phpstan.neon
      - ./phpstan-baseline.neon:/var/www/phpstan-baseline.neon
